name: output-event-issues
on: [push, workflow_dispatch]
jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Context Information
        run: echo "${{ toJson(github) }}"
      - name: GitHub Issues Context Information
        run: echo "${{ toJson(github.issues) }}"
